import pytest
from llmfs.content.plugins.readme import ReadmeGenerator
from llmfs.models.filesystem import FileNode

def create_file_node(content=None):
    """Helper to create a FileNode instance"""
    return FileNode(
        type="file",
        content=content,
        attrs={"st_mode": "33188"},  # 644 permissions
        xattrs={}
    )

def test_proc_path():
    """Test that the readme plugin uses correct proc path"""
    plugin = ReadmeGenerator()
    assert plugin.get_proc_path() == "README"
    
    # Test path handling from ProcPlugin
    assert plugin.can_handle("/.llmfs/README", create_file_node())
    assert not plugin.can_handle("/project/.llmfs/README", create_file_node())  # Only handles root .llmfs
    assert not plugin.can_handle("/README.md", create_file_node())
    assert not plugin.can_handle("/.llmfs/other", create_file_node())

def test_generate_content():
    """Test readme content generation with filesystem structure"""
    plugin = ReadmeGenerator()
    fs_structure = {
        "/": FileNode(
            type="directory",
            children={
                "src": "/src",
                "tests": "/tests"
            },
            attrs={"st_mode": "16877"}
        ),
        "/src": FileNode(
            type="directory",
            children={
                "main.py": "/src/main.py"
            },
            attrs={"st_mode": "16877"}
        ),
        "/src/main.py": FileNode(
            type="file",
            content="print('hello')",
            attrs={"st_mode": "33188"},
            xattrs={"generator": "python"}
        ),
        "/tests": FileNode(
            type="directory",
            children={},
            attrs={"st_mode": "16877"}
        )
    }
    
    content = plugin.generate("/.llmfs/README", create_file_node(), fs_structure)
    
    # Verify content includes expected structure
    assert "Project Structure" in content
    assert "src" in content
    assert "main.py" in content
    assert "[Auto-generated by python plugin]" in content
    assert "tests" in content
