import pytest
from llmfs.content.plugins.readme import ReadmeGenerator
from llmfs.models.filesystem import FileNode

def create_file_node(content=None):
    """Helper to create a FileNode instance"""
    return FileNode(
        type="file",
        content=content,
        attrs={"st_mode": "33188"},  # 644 permissions
        xattrs={}
    )

def test_get_overlay_files():
    """Test that the readme plugin creates overlay file in correct location"""
    plugin = ReadmeGenerator()
    overlays = plugin.get_overlay_files()
    
    assert len(overlays) == 1
    assert overlays[0].path == "/.llmfs/README"
    assert overlays[0].xattrs == {"generator": "readme"}

def test_generate_content():
    """Test readme content generation with filesystem structure"""
    plugin = ReadmeGenerator()
    fs_structure = {
        "/": FileNode(
            type="directory",
            children={
                "src": "/src",
                "tests": "/tests"
            },
            attrs={"st_mode": "16877"}
        ),
        "/src": FileNode(
            type="directory",
            children={
                "main.py": "/src/main.py"
            },
            attrs={"st_mode": "16877"}
        ),
        "/src/main.py": FileNode(
            type="file",
            content="print('hello')",
            attrs={"st_mode": "33188"},
            xattrs={"generator": "python"}
        ),
        "/tests": FileNode(
            type="directory",
            children={},
            attrs={"st_mode": "16877"}
        )
    }
    
    content = plugin.generate("/.llmfs/README", create_file_node(), fs_structure)
    
    # Verify content includes expected structure
    assert "Project Structure" in content
    assert "src" in content
    assert "main.py" in content
    assert "[Auto-generated by python plugin]" in content
    assert "tests" in content
