"""Command line interface for marking files for TouchFS content generation.

This module provides a CLI interface that extends the behavior of the `touch` 
command within TouchFS filesystems - marking files to have their content 
generated by TouchFS.

Key Features:
1. Like touch, creates files if they don't exist
2. Sets generate_content xattr to mark files for content generation
3. Extends touch with --parents/-p flag to create parent directories (like mkdir -p)
4. Handles multiple files in a single command
5. Safe operation with confirmation for non-touchfs paths

The command is particularly useful for:
1. Working with files outside a TouchFS mount that will be moved into one
2. Making the content generation intent explicit in scripts/automation
3. Batch marking multiple files for generation
4. Creating files in non-existent directory structures (with --parents)

The command will warn if the target path is not within a TouchFS filesystem,
since the generate_content xattr only has effect within TouchFS mounts.
"""

import sys
import os
import argparse
from typing import Optional, List, Tuple
from ..config.logger import setup_logging

def is_path_in_touchfs(path: str) -> bool:
    """Check if a path is within a mounted touchfs filesystem.
    
    Args:
        path: Path to check
        
    Returns:
        True if path is within a touchfs mount, False otherwise
    """
    # Get absolute path
    abs_path = os.path.abspath(path)
    
    # Walk up directory tree checking for .touchfs marker
    current = abs_path
    while current != '/':
        if os.path.exists(os.path.join(current, '.touchfs')):
            return True
        current = os.path.dirname(current)
    return False

def parse_args() -> argparse.Namespace:
    """Parse command line arguments.
    
    Returns:
        Parsed command line arguments
    """
    parser = argparse.ArgumentParser(
        description='Mark files for TouchFS content generation (equivalent to touch within TouchFS)',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument(
        'paths',
        nargs='+',
        help='One or more paths to mark for generation'
    )
    parser.add_argument(
        '--force', '-f',
        action='store_true',
        help='Skip confirmation prompt for non-touchfs paths'
    )
    parser.add_argument(
        '--parents', '-p',
        action='store_true',
        help='Create parent directories as needed (like mkdir -p)'
    )
    parser.add_argument(
        '--debug-stderr',
        action='store_true',
        help='Enable debug logging to stderr'
    )
    return parser.parse_args()

def categorize_paths(paths: List[str]) -> Tuple[List[str], List[str]]:
    """Categorize paths into touchfs and non-touchfs lists.
    
    Args:
        paths: List of paths to categorize
        
    Returns:
        Tuple of (touchfs_paths, non_touchfs_paths)
    """
    touchfs_paths = []
    non_touchfs_paths = []
    
    for path in paths:
        abs_path = os.path.abspath(path)
        if is_path_in_touchfs(abs_path):
            touchfs_paths.append(abs_path)
        else:
            non_touchfs_paths.append(abs_path)
            
    return touchfs_paths, non_touchfs_paths

def create_file_with_xattr(path: str, create_parents: bool = False) -> bool:
    """Create a file and set the generate_content xattr.
    
    Args:
        path: Path to file to create and mark
        create_parents: Whether to create parent directories if they don't exist
        
    Returns:
        True if successful, False if error occurred
    """
    try:
        # Handle parent directories
        parent_dir = os.path.dirname(path)
        if parent_dir and not os.path.exists(parent_dir):
            if create_parents:
                os.makedirs(parent_dir)
            else:
                print(f"Error: Parent directory '{parent_dir}' does not exist", file=sys.stderr)
                print("Use --parents/-p to create parent directories", file=sys.stderr)
                return False
            
        # Create file if it doesn't exist
        if not os.path.exists(path):
            with open(path, 'a'):
                pass
                
        # Set xattr
        os.setxattr(path, 'touchfs.generate_content', b'true')
        print(f"Successfully marked '{path}' for TouchFS content generation")
        return True
    except OSError as e:
        print(f"Error processing '{path}': {e}", file=sys.stderr)
        return False

def main(paths: List[str], force: bool = False, parents: bool = False, debug_stderr: bool = False) -> int:
    """Main entry point for generate command.
    
    This command sets the generate_content xattr that TouchFS uses to identify
    files that should have their content generated. Within a TouchFS filesystem,
    this is automatically set by the touch command - this CLI provides an
    explicit way to set the same marker.
    
    Args:
        paths: List of paths to mark for generation
        force: Skip confirmation for non-touchfs paths
        parents: Create parent directories as needed
        debug_stderr: Enable debug logging to stderr
        
    Returns:
        Exit code (0 for success, 1 for error)
    """
    try:
        # Setup logging
        logger = setup_logging(debug_stderr=debug_stderr)
        logger.debug("==== TouchFS Generate Command Started ====")
        
        # Categorize paths
        touchfs_paths, non_touchfs_paths = categorize_paths(paths)
        
        # Early warning about non-touchfs paths
        if non_touchfs_paths:
            print("Warning: The following paths are not within a TouchFS filesystem:")
            for path in non_touchfs_paths:
                print(f"  {path}")
            print("\nNote: The generate_content marker only affects files within TouchFS mounts")
            print("      Using touch within a TouchFS mount automatically sets this marker")
            
            if not force:
                # Prompt for each non-touchfs path
                approved_non_touchfs = []
                for path in non_touchfs_paths:
                    response = input(f"\nDo you want to mark '{path}'? [y/N] ")
                    if response.lower() == 'y':
                        approved_non_touchfs.append(path)
                    
                if not approved_non_touchfs and not touchfs_paths:
                    print("No paths approved for marking")
                    return 0
                    
                non_touchfs_paths = approved_non_touchfs
        
        # Prompt for touchfs paths if any exist and we have approvals/force
        if touchfs_paths and (force or non_touchfs_paths or not len(paths) == len(touchfs_paths)):
            print("\nThe following paths will be marked for generation:")
            for path in touchfs_paths:
                print(f"  {path}")
            response = input("\nDo you want to continue? [Y/n] ")
            if response.lower() == 'n':
                print("No paths approved for marking")
                return 0
        
        # Process all approved paths
        had_error = False
        for path in non_touchfs_paths + touchfs_paths:
            if not create_file_with_xattr(path, create_parents=parents):
                had_error = True
                
        if not had_error:
            print("(This is equivalent to using touch within a TouchFS filesystem)")
            
        # Return 0 even if some paths failed, like touch does
        return 0
            
    except Exception as e:
        if debug_stderr:
            print(f"Error in generate command: {e}", file=sys.stderr)
        return 1

def run():
    """Entry point for the command-line script."""
    args = parse_args()
    sys.exit(main(
        paths=args.paths,
        force=args.force,
        parents=args.parents,
        debug_stderr=args.debug_stderr
    ))
