name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install marked
        run: npm install marked
        
      - name: Convert markdown to HTML
        run: |
          for file in docs/**/*.md docs/*.md; do
            if [ -f "$file" ]; then
              html_file="${file%.md}.html"
              mkdir -p "$(dirname "$html_file")"
              echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>TouchFS Documentation</title><style>.markdown-body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen,Ubuntu,Cantarell,'Open Sans','Helvetica Neue',sans-serif;line-height:1.6;max-width:800px;margin:0 auto;padding:20px}pre{background:#f8f9fa;padding:1rem;border-radius:6px;overflow-x:auto}code{font-family:SFMono-Regular,Consolas,'Liberation Mono',Menlo,monospace;font-size:85%}h1,h2,h3{color:#2c3e50;border-bottom:2px solid #eee;padding-bottom:10px}</style></head><body class='markdown-body'><a href='/touchfs/' style='display:inline-block;margin-bottom:20px;color:#007bff;text-decoration:none'>← Back to Main Page</a>" > "$html_file"
              npx marked "$file" >> "$html_file"
              echo "</body></html>" >> "$html_file"
            fi
          done
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
